/home/bhaeussl/EUCLID/data/FIELD0/SS/cut/ssersic_0_vis_1_1.fits /home/bhaeussl/EUCLID/data/RMS_maps/cut/weight_map_general_1_1.fits /home/bhaeussl/EUCLID/data/FIELD0/SS/cut/ssersic_0_vis.rms_1_1.fits
/home/bhaeussl/EUCLID/data/FIELD0/SS/cut/ssersic_0_vis_1_2.fits /home/bhaeussl/EUCLID/data/RMS_maps/cut/weight_map_general_1_2.fits /home/bhaeussl/EUCLID/data/FIELD0/SS/cut/ssersic_0_vis.rms_1_2.fits
/home/bhaeussl/EUCLID/data/FIELD0/SS/cut/ssersic_0_vis_1_3.fits /home/bhaeussl/EUCLID/data/RMS_maps/cut/weight_map_general_1_3.fits /home/bhaeussl/EUCLID/data/FIELD0/SS/cut/ssersic_0_vis.rms_1_3.fits
/home/bhaeussl/EUCLID/data/FIELD0/SS/cut/ssersic_0_vis_1_4.fits /home/bhaeussl/EUCLID/data/RMS_maps/cut/weight_map_general_1_4.fits /home/bhaeussl/EUCLID/data/FIELD0/SS/cut/ssersic_0_vis.rms_1_4.fits
/home/bhaeussl/EUCLID/data/FIELD0/SS/cut/ssersic_0_vis_1_5.fits /home/bhaeussl/EUCLID/data/RMS_maps/cut/weight_map_general_1_5.fits /home/bhaeussl/EUCLID/data/FIELD0/SS/cut/ssersic_0_vis.rms_1_5.fits
/home/bhaeussl/EUCLID/data/FIELD0/SS/cut/ssersic_0_vis_1_6.fits /home/bhaeussl/EUCLID/data/RMS_maps/cut/weight_map_general_1_6.fits /home/bhaeussl/EUCLID/data/FIELD0/SS/cut/ssersic_0_vis.rms_1_6.fits
/home/bhaeussl/EUCLID/data/FIELD0/SS/cut/ssersic_0_vis_2_1.fits /home/bhaeussl/EUCLID/data/RMS_maps/cut/weight_map_general_2_1.fits /home/bhaeussl/EUCLID/data/FIELD0/SS/cut/ssersic_0_vis.rms_2_1.fits
/home/bhaeussl/EUCLID/data/FIELD0/SS/cut/ssersic_0_vis_2_2.fits /home/bhaeussl/EUCLID/data/RMS_maps/cut/weight_map_general_2_2.fits /home/bhaeussl/EUCLID/data/FIELD0/SS/cut/ssersic_0_vis.rms_2_2.fits
/home/bhaeussl/EUCLID/data/FIELD0/SS/cut/ssersic_0_vis_2_3.fits /home/bhaeussl/EUCLID/data/RMS_maps/cut/weight_map_general_2_3.fits /home/bhaeussl/EUCLID/data/FIELD0/SS/cut/ssersic_0_vis.rms_2_3.fits
/home/bhaeussl/EUCLID/data/FIELD0/SS/cut/ssersic_0_vis_2_4.fits /home/bhaeussl/EUCLID/data/RMS_maps/cut/weight_map_general_2_4.fits /home/bhaeussl/EUCLID/data/FIELD0/SS/cut/ssersic_0_vis.rms_2_4.fits
/home/bhaeussl/EUCLID/data/FIELD0/SS/cut/ssersic_0_vis_2_5.fits /home/bhaeussl/EUCLID/data/RMS_maps/cut/weight_map_general_2_5.fits /home/bhaeussl/EUCLID/data/FIELD0/SS/cut/ssersic_0_vis.rms_2_5.fits
/home/bhaeussl/EUCLID/data/FIELD0/SS/cut/ssersic_0_vis_2_6.fits /home/bhaeussl/EUCLID/data/RMS_maps/cut/weight_map_general_2_6.fits /home/bhaeussl/EUCLID/data/FIELD0/SS/cut/ssersic_0_vis.rms_2_6.fits
/home/bhaeussl/EUCLID/data/FIELD0/SS/cut/ssersic_0_vis_3_1.fits /home/bhaeussl/EUCLID/data/RMS_maps/cut/weight_map_general_3_1.fits /home/bhaeussl/EUCLID/data/FIELD0/SS/cut/ssersic_0_vis.rms_3_1.fits
/home/bhaeussl/EUCLID/data/FIELD0/SS/cut/ssersic_0_vis_3_2.fits /home/bhaeussl/EUCLID/data/RMS_maps/cut/weight_map_general_3_2.fits /home/bhaeussl/EUCLID/data/FIELD0/SS/cut/ssersic_0_vis.rms_3_2.fits
/home/bhaeussl/EUCLID/data/FIELD0/SS/cut/ssersic_0_vis_3_3.fits /home/bhaeussl/EUCLID/data/RMS_maps/cut/weight_map_general_3_3.fits /home/bhaeussl/EUCLID/data/FIELD0/SS/cut/ssersic_0_vis.rms_3_3.fits
/home/bhaeussl/EUCLID/data/FIELD0/SS/cut/ssersic_0_vis_3_4.fits /home/bhaeussl/EUCLID/data/RMS_maps/cut/weight_map_general_3_4.fits /home/bhaeussl/EUCLID/data/FIELD0/SS/cut/ssersic_0_vis.rms_3_4.fits
/home/bhaeussl/EUCLID/data/FIELD0/SS/cut/ssersic_0_vis_3_5.fits /home/bhaeussl/EUCLID/data/RMS_maps/cut/weight_map_general_3_5.fits /home/bhaeussl/EUCLID/data/FIELD0/SS/cut/ssersic_0_vis.rms_3_5.fits
/home/bhaeussl/EUCLID/data/FIELD0/SS/cut/ssersic_0_vis_3_6.fits /home/bhaeussl/EUCLID/data/RMS_maps/cut/weight_map_general_3_6.fits /home/bhaeussl/EUCLID/data/FIELD0/SS/cut/ssersic_0_vis.rms_3_6.fits
/home/bhaeussl/EUCLID/data/FIELD0/SS/cut/ssersic_0_vis_4_1.fits /home/bhaeussl/EUCLID/data/RMS_maps/cut/weight_map_general_4_1.fits /home/bhaeussl/EUCLID/data/FIELD0/SS/cut/ssersic_0_vis.rms_4_1.fits
/home/bhaeussl/EUCLID/data/FIELD0/SS/cut/ssersic_0_vis_4_2.fits /home/bhaeussl/EUCLID/data/RMS_maps/cut/weight_map_general_4_2.fits /home/bhaeussl/EUCLID/data/FIELD0/SS/cut/ssersic_0_vis.rms_4_2.fits
/home/bhaeussl/EUCLID/data/FIELD0/SS/cut/ssersic_0_vis_4_3.fits /home/bhaeussl/EUCLID/data/RMS_maps/cut/weight_map_general_4_3.fits /home/bhaeussl/EUCLID/data/FIELD0/SS/cut/ssersic_0_vis.rms_4_3.fits
/home/bhaeussl/EUCLID/data/FIELD0/SS/cut/ssersic_0_vis_4_4.fits /home/bhaeussl/EUCLID/data/RMS_maps/cut/weight_map_general_4_4.fits /home/bhaeussl/EUCLID/data/FIELD0/SS/cut/ssersic_0_vis.rms_4_4.fits
/home/bhaeussl/EUCLID/data/FIELD0/SS/cut/ssersic_0_vis_4_5.fits /home/bhaeussl/EUCLID/data/RMS_maps/cut/weight_map_general_4_5.fits /home/bhaeussl/EUCLID/data/FIELD0/SS/cut/ssersic_0_vis.rms_4_5.fits
/home/bhaeussl/EUCLID/data/FIELD0/SS/cut/ssersic_0_vis_4_6.fits /home/bhaeussl/EUCLID/data/RMS_maps/cut/weight_map_general_4_6.fits /home/bhaeussl/EUCLID/data/FIELD0/SS/cut/ssersic_0_vis.rms_4_6.fits
/home/bhaeussl/EUCLID/data/FIELD0/SS/cut/ssersic_0_vis_5_1.fits /home/bhaeussl/EUCLID/data/RMS_maps/cut/weight_map_general_5_1.fits /home/bhaeussl/EUCLID/data/FIELD0/SS/cut/ssersic_0_vis.rms_5_1.fits
/home/bhaeussl/EUCLID/data/FIELD0/SS/cut/ssersic_0_vis_5_2.fits /home/bhaeussl/EUCLID/data/RMS_maps/cut/weight_map_general_5_2.fits /home/bhaeussl/EUCLID/data/FIELD0/SS/cut/ssersic_0_vis.rms_5_2.fits
/home/bhaeussl/EUCLID/data/FIELD0/SS/cut/ssersic_0_vis_5_3.fits /home/bhaeussl/EUCLID/data/RMS_maps/cut/weight_map_general_5_3.fits /home/bhaeussl/EUCLID/data/FIELD0/SS/cut/ssersic_0_vis.rms_5_3.fits
/home/bhaeussl/EUCLID/data/FIELD0/SS/cut/ssersic_0_vis_5_4.fits /home/bhaeussl/EUCLID/data/RMS_maps/cut/weight_map_general_5_4.fits /home/bhaeussl/EUCLID/data/FIELD0/SS/cut/ssersic_0_vis.rms_5_4.fits
/home/bhaeussl/EUCLID/data/FIELD0/SS/cut/ssersic_0_vis_5_5.fits /home/bhaeussl/EUCLID/data/RMS_maps/cut/weight_map_general_5_5.fits /home/bhaeussl/EUCLID/data/FIELD0/SS/cut/ssersic_0_vis.rms_5_5.fits
/home/bhaeussl/EUCLID/data/FIELD0/SS/cut/ssersic_0_vis_5_6.fits /home/bhaeussl/EUCLID/data/RMS_maps/cut/weight_map_general_5_6.fits /home/bhaeussl/EUCLID/data/FIELD0/SS/cut/ssersic_0_vis.rms_5_6.fits
/home/bhaeussl/EUCLID/data/FIELD0/SS/cut/ssersic_0_vis_6_1.fits /home/bhaeussl/EUCLID/data/RMS_maps/cut/weight_map_general_6_1.fits /home/bhaeussl/EUCLID/data/FIELD0/SS/cut/ssersic_0_vis.rms_6_1.fits
/home/bhaeussl/EUCLID/data/FIELD0/SS/cut/ssersic_0_vis_6_2.fits /home/bhaeussl/EUCLID/data/RMS_maps/cut/weight_map_general_6_2.fits /home/bhaeussl/EUCLID/data/FIELD0/SS/cut/ssersic_0_vis.rms_6_2.fits
/home/bhaeussl/EUCLID/data/FIELD0/SS/cut/ssersic_0_vis_6_3.fits /home/bhaeussl/EUCLID/data/RMS_maps/cut/weight_map_general_6_3.fits /home/bhaeussl/EUCLID/data/FIELD0/SS/cut/ssersic_0_vis.rms_6_3.fits
/home/bhaeussl/EUCLID/data/FIELD0/SS/cut/ssersic_0_vis_6_4.fits /home/bhaeussl/EUCLID/data/RMS_maps/cut/weight_map_general_6_4.fits /home/bhaeussl/EUCLID/data/FIELD0/SS/cut/ssersic_0_vis.rms_6_4.fits
/home/bhaeussl/EUCLID/data/FIELD0/SS/cut/ssersic_0_vis_6_5.fits /home/bhaeussl/EUCLID/data/RMS_maps/cut/weight_map_general_6_5.fits /home/bhaeussl/EUCLID/data/FIELD0/SS/cut/ssersic_0_vis.rms_6_5.fits
/home/bhaeussl/EUCLID/data/FIELD0/SS/cut/ssersic_0_vis_6_6.fits /home/bhaeussl/EUCLID/data/RMS_maps/cut/weight_map_general_6_6.fits /home/bhaeussl/EUCLID/data/FIELD0/SS/cut/ssersic_0_vis.rms_6_6.fits
